name: Deploy Backend to Render

on:
  push:
   #branches: [main, newmain]
    paths:
      - 'backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render Deploy Hook
        run: |
          curl -f "${{ secrets.RENDER_DEPLOY_HOOK_URL }}"